### PR TITLE
Make it possible to mark services as ipv6-only [seperate JS]

### PR DESCRIPTION
**Pull request by puiterwijk**
Seperate JS version of #27

### CODE REVIEW

**Comment by ralphbean** [comment]
Could you include instructions in the the is_ipv6.js file (or in the README) on how to configure apache to do that correctly?

**Comment by pypingou** [comment]
@puiterwijk ?

**Comment by pypingou** [comment]
@puiterwijk looks like it'll need a rebase as well :)

**Comment by ralphbean** [comment]
Since `is_ipv6` is almost always `false`, can we make it default to that in the yaml-to-json script?  That way we can avoid being repetitive in the yaml file.

**Comment by ralphbean** [comment]
Great.  Thank you :)

**Pull request merged**
