### PR TITLE
Re-doing Landing page

### PR DESCRIPTION
**Pull request by Peppa-Peddler**
Built a zoomable svg-graph with D3 to replace the old landing page. Some old files may need to be erased.

### CODE REVIEW

**Comment by puiterwijk** [comment]
I have multiple issues with this:
- Why are you bundling the world? This diff is way too huge.
- I don't like the fact that until you click on a level, you have no idea what's in them. for example, I wouldn't have expected Notifications under Accounts, so then I have to search through all of them to find it.

**Comment by genodeftest** [comment]
Feedback (assuming you want to fix #37):
* I think the UI should be more responsive to different browser window sizes. Only if page width > 1400px (or 900px in narrow mode) the circle "packaging" isn't cut off. At a width of 1200px (or 800px) even the label "packaging" is cut off, not only the circle. At a width of 1000px (or 700px) the label "packaging" isn't visible any more at all. At a width of 600px the "packaging" circle isn't visible at all any more. With narrow screens the "X [category]" is misplaced, not on top left any more. The ["Responsive Design Mode"](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) of firefox inspector might help you.
* After clicking on a category (e.g. Infrastructure), how about displaying "Infrastructure" inside the bigger circle?
* How about making "click outside the circle" act the same as pressing the "X" button?

You don't need to keep the "circles" metaphor if that is too hard to implement, especially with responsivity. Having just lists probably is enough, e.g. like this:
```

    [Page header]
    

Infrastructure    | [General description]
Accounts          |
Content           |
Upstream          |
Coordination      |
…
```
Then, after a user selects a category:
```

    [Page header]
    

Infrastructure <- | Nagios         | [Description for category
Accounts          | MirrorManager  |    "Infrastructure"]
Content           | Collectd       | 
Upstream          | GeoIP          | 
Coordination      | Status
…                 | …

```

After the user selects a page:
```

    [Page header]
    

Infrastructure <- | Nagios         | [Description for "Status"]
Accounts          | MirrorManager  |
Content           | Collectd       | 
Upstream          | GeoIP          | 
Coordination      | Status      <- |
…                 | …
```

This approach would be less visually appealing (I guess), but it would be way easier to implement with responsivity in mind. If these 2 to 3 columns are too wide, just display them below each other instead of besides.

Last but not least it would be nice to have a full-text search that if I want to search for "mirror", I'll see "MirrorManager" or if I search for "blog" I get "The Planet".

**Comment by Peppa-Peddler** [comment]
Thanks guys for the your review, I think I need to keep working on the responsive version as you pointed out.

@puiterwijk having a huge amount of apps visible isn't a good idea I think. Even worst when displayed for small screens.

@genodeftest You are right i will keep working on the details, but do you think I should keep my idea or work again on a different graph like the one you described?

**Comment by Peppa-Peddler** [comment]
@genodeftest anyway for now I will work on the three points you mentioned:
-UI size
-Click event on category
-Zoom usability

**Comment by genodeftest** [comment]
@Peppa-Peddler 
> do you think I should keep my idea or work again on a different graph like the one you described?

I don't know, that's up to you to decide, both solutions are possible. I like mine more because I like simplicity, but yours is closer to the current design which means less change – and probably a better user experience because it is more intuitive.

**Comment by pypingou** [comment]
This PR has been opened for a while and without activity for more than a months. I am therefore going to close it.

That is not to say that we reject this change per say, merely an attempt to keep our list of open pull-request manageable.

Please re-open, this PR or another one as you like when you have more to show or discuss :)

Thanks for your work!

**Pull request closed without merging**
