### PR TITLE
Use handlebars.js for templating.

### PR DESCRIPTION
**Pull request by ralphbean**
This is kinda overkill..  but it's still simpler than the server-side approach
in #32.  This is just experimenting to get the hang of what @rtnpro is doing
with the fedora releng-dash.

### CODE REVIEW

**Comment by puiterwijk** [comment]
Looks good to me. Thanks! :+1:

**Comment by ralphbean** [comment]
Thanks, @puiterwijk!

**Comment by pypingou** [comment]
This is pretty cool :)

**Comment by rtnpro** [comment]
:+1:

**Pull request merged**
