### PR TITLE
Cgit was replaced with Pagure for package sources.

### LINKED ISSUE #55: SCM Link points to invalid location
https://apps.fedoraproject.org/#Packages

SCM still points to: https://src.fedoraproject.org/cgit

I think it should probably just be https://src.fedoraproject.org/ by now, or maybe a new icon for "Pagure over dist-git", and removal of the SCM endpoint.

### PR DESCRIPTION
**Pull request by mavit**
Fixes #55.

### CODE REVIEW

**Review by bowlofeggs — APPROVED** [review]

**Comment by pypingou** [comment]
👍 for me as well, but we'll need to fix this in ansible as well :)

**Comment by Zlopez** [comment]
Is this still not ready for merge?

**Comment by pypingou** [comment]
let's get this in

**Comment by troycurtisjr** [comment]
It seems like this PR should address #60 as well, but it doesn't appear to be live on the web page yet.

**Pull request merged**
