### PR TITLE
Redesign apps.fp.o

### LINKED ISSUE #37: apps.fp.o is hard to read and hard to use
The current apps.fp.o landing page looks like this:
apps fp o

It has several usability problems:
1. some items (in this case most of what's below Packaging) are not accessible because they are hidden behind the description
2. there is no useful content without javascript. This is bad for search engines or users with limited browser functionality.
3. if you select a leaf node everything changes. This is disturbing the user.
4. it is barely usable on smaller screens (vertical+horizontal scrolling) due to its fixed size.
5. text overlaps, making it hard to read and pick leaf nodes.

How about a structured list, more like fedmenu plus a sidebar showing the description(s)? additionally a full text search in descriptions would be useful for people new to fedoraproject.

### LINKED ISSUE #55: SCM Link points to invalid location
https://apps.fedoraproject.org/#Packages

SCM still points to: https://src.fedoraproject.org/cgit

I think it should probably just be https://src.fedoraproject.org/ by now, or maybe a new icon for "Pagure over dist-git", and removal of the SCM endpoint.

### PR DESCRIPTION
**Pull request by mymindstorm**
Closes #37 
025f23d9941b6a654196d7d09d62d5828794fc3e closes #55 #56 fedora-infra/fedmenu#22

This is my initial attempt to make apps.fp.o more readable. I'm not a designer, so it needs a bit of work.

[Screenshot](https://user-images.githubusercontent.com/27789806/46838377-a6094980-cd7e-11e8-90ee-10f30e1cf9a6.png)

The Ipsilon link is broken, should it go [here](https://ipsilon-project.org/)?
Should https://discussion.fedoraproject.org/ and https://budget.fedoraproject.org/ be added?

### CODE REVIEW

**Review by Zlopez — APPROVED** [review]
LGTM
I just recommend squashing the commits, when you think it is ready for merge

**Comment by pypingou** [comment]
This makes it a very long list that's not very fun to look at :(

**Comment by mymindstorm** [comment]
@pypingou any suggestions? What about adding a fedmenu style list at the the top with quick links?

**Comment by pypingou** [comment]
@mymindstorm to be honest not really, it's a tough page to (re)design :(

**Comment by mymindstorm** [comment]
@pypingou been thinking about this for a while, and I'm not really sure how to make a list of things "fun" (well, not without sacrificing UX like the current design does). Anyway, I looked around at what other people did with really big lists and have a few ideas before giving up and closing this completely unless you have some ideas.

1. Slap a few featured / frequent things at the top  of the boring list
    a. Potentially make the list two columns if screen is big enough
    b. Make sections more distinct?
    c. Make item names stand out more?
    d. Too much to take in with current list. Reduce descriptions to one sentence 
2. Change format to a list of categories on the left and on hover / click reveal a short list on the right side of the page
    a. default category on page load could be frequent things

**Comment by Siosm** [comment]
I think better is the enemy of good here. This is indeed a big list but the current page has legibility and accessibility issues that are solved by this redesign / simpler design. Incremental improvements could come later. Moreover the current page is already outdated (https://discussion.fedoraproject.org is not there for example).

**Comment by mymindstorm** [comment]
That's mostly the reason I made this in the first place. I know the design isn't the best, but I want to be able to ctrl + f and find a service quickly. I also can't actually click on all of the services sometimes because my laptop's screen is too small.

**Comment by Siosm** [comment]
@mymindstorm May I suggest that you squash all your commits as requested so that this can get approved and merged. Then I think we should discuss adding new services and doing some re-ordering.

**Comment by mymindstorm** [comment]
@Siosm it looks like this doesn't matter anymore as apps.fp.o will be deprecated.
https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/NETZC5J3Z3MLCIYJMW5U7ROSLO6BDILH/

**Comment by mymindstorm** [comment]
@pypingou @Zlopez It looks like y'all are about to switch over the domain to the new version, this will break fedmenu if you weren't aware already. I'm willing to maintain fedmenu and apps.fp.o, but it looks like it's already too late for me to offer that.

https://github.com/fedora-infra/fedmenu/blob/8fb6fde588c67f6836397311efc862ccbf1306e5/js/fedmenu.js#L3

**Comment by pypingou** [comment]
> It looks like y'all are about to switch over the domain to the new version

I am not aware that we are, but fedmenu is being deprecated anyway, it has already been removed from a number of our applications.

apps.fp.o is also going to be retired, in favor of a page in the infra docs hosted at docs.fedoraproject.org. The first work toward this can be seen at: https://pagure.io/infra-docs-fpo/pull-request/1

**Review by Caterrsa — APPROVED** [review]

**Comment by FrostyX** [comment]
I just got a notification on this PR. No idea what is the status here and what are the future plans for https://apps.fedoraproject.org but for the record, some time ago I did an unofficial rewrite of the apps page, so please allow me to make a shameless plug here:

Instance: https://fedora-apps.netlify.app/
Upstream: https://github.com/FrostyX/fedora-apps

It never got accepted and used in production but in case anybody was interested in moving forward on that front, please let me know.

**Pull request closed without merging**
