### PR TITLE
Update apps.fp.o to fedora-bootstrap

### PR DESCRIPTION
**Pull request by ryanlerch**
A quick change to add the Fedora Boostrap style to apps.fp.o

### CODE REVIEW

**Comment by pypingou** [comment]
Do you have a screenshot handy?

**Comment by bowlofeggs** [comment]
The code LGTM, but I haven't rendered it myself to see what it looks like.

**Comment by ryanlerch** [comment]
I don't have one screenshot. I have two. :D

apps2
apps1

**Comment by pypingou** [comment]
Looks neat, 👍 for me :)

**Comment by ryanlerch** [comment]
@pypingou is this one right to merge?

**Comment by pypingou** [comment]
👍 it then, 👍 'ng it now :)

**Pull request merged**
